[{
  "src": "./img/asset-opti/AstroBase.png",
  "name": "AstroBase",
  "images": [
    "corridor_open",
    "corridor_windowClosed",
    "corridor_",
    "corridor_cornerRoundWindow",
    "corridor_cross",
    "corridor_corner",
    "corridor_window",
    "corridor_detailed",
    "corridor_end",
    "corridor_cornerRound",
    "corridor_roof",
    "corridor_split",
    "corridor_wallCorner",
    "corridor_wall",
  ],
  "imgHeight": 224,
  "imgWidth": 192,
  "type": "building",
}]