[{
  "src": "./img/asset-opti/ItemPilar.png",
  "group": "ItemPilar",
  "images": [
    "statue_column",
    "statue_ring",
    "statue_obelisk",
    "pillarSquare",
    "statue_head",
    "pillarObelisk",
    "statue_block",
    "pillarLarge",
    "borderPillar",
    "pillarSmall",
    "statue_columnDamaged",
    "columnLarge",
  ],
  "imgHeight": 224,
  "imgWidth": 192,
}]