[{
  "src": "./img/asset-opti/ItemGrave.png",
  "group": "ItemGrave",
  "images": [
    "gravestoneDecorative",
    "coffinOld",
    "gravestoneRound",
    "altarStone",
    "gravestoneBevel",
    "crypt",
    "gravestoneFlat",
    "gravestoneRoof",
    "gravestoneFlatOpen",
    "gravestoneWide",
    "coffin",
    "altarWood",
  ],
  "imgHeight": 224,
  "imgWidth": 192,
}]