[{
  "src": "./img/asset-opti/ItemOther.png",
  "name": "ItemOther",
  "images": [
    "crate",
    "barrel",
    "detailPlate",
    "bench",
    "heart",
    "campfire_logs",
    "flag",
    "chest",
    "chimney",
    "spikesHidden",
    "key",
    "crateStrong",
    "coinSilver",
    "bones",
    "road",
    "detailBowl",
    "crateItemStrong",
    "benchDamaged",
    "coinGold",
    "spikesLarge",
    "detailChalice",
    "sign",
    "chimney_detailed",
    "jewel",
    "urn",
    "arrows",
    "tent_detailedClosed",
    "arrow",
    "crateItem",
    "spikes",
    "tent_detailedOpen",
    "campfire_stones",
    "coinBronze",
  ],
  "imgHeight": 224,
  "imgWidth": 192,
    "type": "items",

}]