[{
  "src": "./img/asset-opti/NatureTree.png",
  "group": "NatureTree",
  "scall": true,
  "images":  [
    "tree_detailed",
    "tree_thin_fall",
    "tree_palmShort",
    "tree_small",
    "tree_pineDefaultA",
    "tree_thin_dark",
    "cactus_tall",
    "tree_pineRoundE",
    "tree_cone",
    "tree_tall_dark",
    "tree_blocks_fall",
    "tree_cone_fall",
    "tree_default_fall",
    "tree_pineTallC",
    "tree_pineRoundA",
    "tree_simple_dark",
    "tree_pineRoundC",
    "tree_simple_fall",
    "tree_pineTallA",
    "tree_default",
    "tree_simple",
    "tree_default_dark",
    "tree_cone_dark",
    "tree_tall_fall",
    "tree_pineSmallA",
    "tree_blocks_dark",
    "tree_palmTall",
    "tree_thin",
    "tree_pineSmallD",
    "tree_fat",
    "tree_fat_darkh",
    "tree_oak_fall",
    "tree_pineTallD",
    "tree_plateau_fall",
    "tree_detailed_dark",
    "tree_palmBend",
    "tree_pineRoundD",
    "tree_detailed_fall",
    "tree_oak_dark",
    "tree_plateau_dark",
    "tree_palmDetailedShort",
    "cactus_short",
    "tree_small_fall",
    "tree_pineTallB",
    "tree_palmDetailedTall",
    "tree_fat_fall",
    "tree_pineSmallB",
    "tree_blocks",
    "tree_palm",
    "tree_oak",
    "tree_pineGroundA",
    "tree_tall",
    "tree_small_dark",
    "tree_pineRoundB",
    "tree_plateau",
  ],
  "imgHeight": 224,
  "imgWidth": 192,
}]