[{
  "src": "./img/asset-opti/Wall.png",
  "group": "Wall",
  "images": [
    "fence_simpleLow",
    "fenceGate",
    "fence_bend",
    "doorClosed",
    "fence_simpleDiagonal",
    "fence_gate",
    "doorOpen",
    "hedge",
    "fence_simpleHigh",
    "fence_planks",
    "ironFenceBorder",
    "fence_simpleCenter",
    "fence_bendCenter",
    "fence_simpleDiagonalCenter",
    "brickWallCurve",
    "stoneWallDamaged",
    "fence_planksDouble",
    "brickWall",
    "stoneWall",
    "ironFence",
    "stoneWallCurve",
    "ironFenceBar",
    "rail_middle",
    "hedgeCorner",
    "ironFenceDamaged",
    "fence_corner",
    "ironFenceBorderColumn",
    "ironFenceCurve",
    "fence_simple",
    "ironFenceBorderGate",
    "rail_end",
    "fence_",
    "rail_corner",
    "stoneWallColumn",
    "ironFenceBorderCurve",
    "fenceDamaged",
    "rail",
  ],
  "imgHeight": 224,
  "imgWidth": 192,
}]