import { TypeAssetGroupConfig } from "../assetOptiConfig.ts";

export const asset_persoCity: TypeAssetGroupConfig = {
  "src": "./img/asset-items/perso-3-anim-city.png",
  "group": "PersoCity",
  "imgHeight": 224,
  "imgWidth": 192,
  "imgType": "perso",
  "images": [
    { "label": "PersoCity-01" },
    { "label": "PersoCity-02" },
    { "label": "PersoCity-03" },
    { "label": "PersoCity-04" },
    { "label": "PersoCity-05" },
    { "label": "PersoCity-06" },
    { "label": "PersoCity-07" },
    { "label": "PersoCity-08" },
    { "label": "PersoCity-09" },
    { "label": "PersoCity-10" },
    { "label": "PersoCity-11" },
    { "label": "PersoCity-12" },
    { "label": "PersoCity-13" },
    { "label": "PersoCity-14" },
    { "label": "PersoCity-15" },
    { "label": "PersoCity-16" },
    { "label": "PersoCity-17" },
    { "label": "PersoCity-18" },
    { "label": "PersoCity-19" },
    { "label": "PersoCity-20" },
    { "label": "PersoCity-21" },
    { "label": "PersoCity-22" },
    { "label": "PersoCity-23" },
    { "label": "PersoCity-24" },
    { "label": "PersoCity-25" },
    { "label": "PersoCity-26" },
    { "label": "PersoCity-27" },
  ],
};
