import { TypeAssetGroupConfig } from "../assetOptiConfig.ts";
import { list_to_asset } from "../assetUtils.ts";

export const asset_ItemOther : TypeAssetGroupConfig = {
  "src": "./img/asset_opti/ItemOther.png",
  "group": "ItemOther",
  "images": list_to_asset([
    "crate",
    "barrel",
    "detailPlate",
    "bench",
    "heart",
    "campfire_logs",
    "flag",
    "chest",
    "chimney",
    "spikesHidden",
    "key",
    "crateStrong",
    "coinSilver",
    "bones",
    "road",
    "detailBowl",
    "crateItemStrong",
    "benchDamaged",
    "coinGold",
    "spikesLarge",
    "detailChalice",
    "sign",
    "chimney_detailed",
    "jewel",
    "urn",
    "arrows",
    "tent_detailedClosed",
    "arrow",
    "crateItem",
    "spikes",
    "tent_detailedOpen",
    "campfire_stones",
    "coinBronze",
  ]),
  "imgHeight": 224,
  "imgWidth": 192,
}