import { TypeAssetGroupConfig } from "../assetOptiConfig.ts";
import { list_to_asset } from "../assetUtils.ts";

export const asset_NatureFlower : TypeAssetGroupConfig = {
  "src": "./img/asset_opti/NatureFlower.png",
  "group": "NatureFlower",
  "scall": true,
  "images": list_to_asset([
    "mushroom_redTall",
    "crops_bambooStageB",
    "crops_cornStageA",
    "flower_purpleA",
    "grass_large",
    "crops_cornStageC",
    "flower_purpleC",
    "flower_redB",
    "grass",
    "crops_wheatStageB",
    "plant_flatTall",
    "flower_yellowC",
    "plant_bushLarge",
    "mushroom_tan",
    "flower_yellowA",
    "plant_bush",
    "plant_bushSmall",
    "crops_leafsStageA",
    "lily_small",
    "mushroom_redGroup",
    "plant_bushDetailed",
    "flower_redA",
    "mushroom_red",
    "crops_bambooStageA",
    "flower_redC",
    "lily_large",
    "flower_purpleB",
    "crops_cornStageB",
    "plant_flatShort",
    "grass_leafs",
    "mushroom_tanTall",
    "flower_yellowB",
    "plant_bushTriangle",
    "crops_leafsStageB",
    "grass_leafsLarge",
    "mushroom_tanGroup",
    "crops_cornStageD",
    "crops_wheatStageA",
    "plant_bushLargeTriangle",
  ]),
  "imgHeight": 224,
  "imgWidth": 192,
}