
import { AssetConfigLoaded } from "./assetConfigLoader.ts";

export const gen_asset_configs = [
  {
    "src": "./img/asset-items/grok-clean-1.png",
    "name": "grok-clean-1",
    "imgHeight": 224,
    "imgWidth": 192,
    "assetCount": 62,
    "type": "items-single",
    "images": [
      "grok-clean-1-0",
      "grok-clean-1-1",
      "grok-clean-1-2",
      "grok-clean-1-3",
      "grok-clean-1-4",
      "grok-clean-1-5",
      "grok-clean-1-6",
      "grok-clean-1-7",
      "grok-clean-1-8",
      "grok-clean-1-9",
      "grok-clean-1-10",
      "grok-clean-1-11",
      "grok-clean-1-12",
      "grok-clean-1-13",
      "grok-clean-1-14",
      "grok-clean-1-15",
      "grok-clean-1-16",
      "grok-clean-1-17",
      "grok-clean-1-18",
      "grok-clean-1-19",
      "grok-clean-1-20",
      "grok-clean-1-21",
      "grok-clean-1-22",
      "grok-clean-1-23",
      "grok-clean-1-24",
      "grok-clean-1-25",
      "grok-clean-1-26",
      "grok-clean-1-27",
      "grok-clean-1-28",
      "grok-clean-1-29",
      "grok-clean-1-30",
      "grok-clean-1-31",
      "grok-clean-1-32",
      "grok-clean-1-33",
      "grok-clean-1-34",
      "grok-clean-1-35",
      "grok-clean-1-36",
      "grok-clean-1-37",
      "grok-clean-1-38",
      "grok-clean-1-39",
      "grok-clean-1-40",
      "grok-clean-1-41",
      "grok-clean-1-42",
      "grok-clean-1-43",
      "grok-clean-1-44",
      "grok-clean-1-45",
      "grok-clean-1-46",
      "grok-clean-1-47",
      "grok-clean-1-48",
      "grok-clean-1-49",
      "grok-clean-1-50",
      "grok-clean-1-51",
      "grok-clean-1-52",
      "grok-clean-1-53",
      "grok-clean-1-54",
      "grok-clean-1-55",
      "grok-clean-1-56",
      "grok-clean-1-57",
      "grok-clean-1-58",
      "grok-clean-1-59",
      "grok-clean-1-60",
      "grok-clean-1-61"
    ],
    "scall": 1
  },
  {
    "src": "./img/asset-items/fences.png",
    "name": "Fences",
    "imgHeight": 224,
    "imgWidth": 192,
    "assetCount": 37,
    "type": "building",
    "images": [
      "Fences-0",
      "Fences-1",
      "Fences-2",
      "Fences-3",
      "Fences-4",
      "Fences-5",
      "Fences-6",
      "Fences-7",
      "Fences-8",
      "Fences-9",
      "Fences-10",
      "Fences-11",
      "Fences-12",
      "Fences-13",
      "Fences-14",
      "Fences-15",
      "Fences-16",
      "Fences-17",
      "Fences-18",
      "Fences-19",
      "Fences-20",
      "Fences-21",
      "Fences-22",
      "Fences-23",
      "Fences-24",
      "Fences-25",
      "Fences-26",
      "Fences-27",
      "Fences-28",
      "Fences-29",
      "Fences-30",
      "Fences-31",
      "Fences-32",
      "Fences-33",
      "Fences-34",
      "Fences-35",
      "Fences-36"
    ],
    "scall": 1
  },
  {
    "src": "./img/asset-items/perso-3-anim-city.png",
    "name": "perso-3-anim-city",
    "imgHeight": 224,
    "imgWidth": 192,
    "assetCount": 52,
    "type": "perso",
    "images": [
      "perso-3-anim-city-0",
      "perso-3-anim-city-1",
      "perso-3-anim-city-2",
      "perso-3-anim-city-3",
      "perso-3-anim-city-4",
      "perso-3-anim-city-5",
      "perso-3-anim-city-6",
      "perso-3-anim-city-7",
      "perso-3-anim-city-8",
      "perso-3-anim-city-9",
      "perso-3-anim-city-10",
      "perso-3-anim-city-11",
      "perso-3-anim-city-12",
      "perso-3-anim-city-13",
      "perso-3-anim-city-14",
      "perso-3-anim-city-15",
      "perso-3-anim-city-16",
      "perso-3-anim-city-17",
      "perso-3-anim-city-18",
      "perso-3-anim-city-19",
      "perso-3-anim-city-20",
      "perso-3-anim-city-21",
      "perso-3-anim-city-22",
      "perso-3-anim-city-23",
      "perso-3-anim-city-24",
      "perso-3-anim-city-25",
      "perso-3-anim-city-26",
      "perso-3-anim-city-27",
      "perso-3-anim-city-28",
      "perso-3-anim-city-29",
      "perso-3-anim-city-30",
      "perso-3-anim-city-31",
      "perso-3-anim-city-32",
      "perso-3-anim-city-33",
      "perso-3-anim-city-34",
      "perso-3-anim-city-35",
      "perso-3-anim-city-36",
      "perso-3-anim-city-37",
      "perso-3-anim-city-38",
      "perso-3-anim-city-39",
      "perso-3-anim-city-40",
      "perso-3-anim-city-41",
      "perso-3-anim-city-42",
      "perso-3-anim-city-43",
      "perso-3-anim-city-44",
      "perso-3-anim-city-45",
      "perso-3-anim-city-46",
      "perso-3-anim-city-47",
      "perso-3-anim-city-48",
      "perso-3-anim-city-49",
      "perso-3-anim-city-50",
      "perso-3-anim-city-51"
    ],
    "scall": 1
  },
  {
    "src": "./img/asset-items/perso-3-anim-nud.png",
    "name": "perso-3-anim-nud",
    "imgHeight": 224,
    "imgWidth": 192,
    "assetCount": 26,
    "type": "perso",
    "images": [
      "perso-3-anim-nud-0",
      "perso-3-anim-nud-1",
      "perso-3-anim-nud-2",
      "perso-3-anim-nud-3",
      "perso-3-anim-nud-4",
      "perso-3-anim-nud-5",
      "perso-3-anim-nud-6",
      "perso-3-anim-nud-7",
      "perso-3-anim-nud-8",
      "perso-3-anim-nud-9",
      "perso-3-anim-nud-10",
      "perso-3-anim-nud-11",
      "perso-3-anim-nud-12",
      "perso-3-anim-nud-13",
      "perso-3-anim-nud-14",
      "perso-3-anim-nud-15",
      "perso-3-anim-nud-16",
      "perso-3-anim-nud-17",
      "perso-3-anim-nud-18",
      "perso-3-anim-nud-19",
      "perso-3-anim-nud-20",
      "perso-3-anim-nud-21",
      "perso-3-anim-nud-22",
      "perso-3-anim-nud-23",
      "perso-3-anim-nud-24",
      "perso-3-anim-nud-25"
    ],
    "scall": 1
  },
  {
    "src": "./img/asset-items/perso-3-city.png",
    "name": "perso-3-city",
    "imgHeight": 224,
    "imgWidth": 192,
    "assetCount": 54,
    "type": "perso",
    "images": [
      "perso-3-city-0",
      "perso-3-city-1",
      "perso-3-city-2",
      "perso-3-city-3",
      "perso-3-city-4",
      "perso-3-city-5",
      "perso-3-city-6",
      "perso-3-city-7",
      "perso-3-city-8",
      "perso-3-city-9",
      "perso-3-city-10",
      "perso-3-city-11",
      "perso-3-city-12",
      "perso-3-city-13",
      "perso-3-city-14",
      "perso-3-city-15",
      "perso-3-city-16",
      "perso-3-city-17",
      "perso-3-city-18",
      "perso-3-city-19",
      "perso-3-city-20",
      "perso-3-city-21",
      "perso-3-city-22",
      "perso-3-city-23",
      "perso-3-city-24",
      "perso-3-city-25",
      "perso-3-city-26",
      "perso-3-city-27",
      "perso-3-city-28",
      "perso-3-city-29",
      "perso-3-city-30",
      "perso-3-city-31",
      "perso-3-city-32",
      "perso-3-city-33",
      "perso-3-city-34",
      "perso-3-city-35",
      "perso-3-city-36",
      "perso-3-city-37",
      "perso-3-city-38",
      "perso-3-city-39",
      "perso-3-city-40",
      "perso-3-city-41",
      "perso-3-city-42",
      "perso-3-city-43",
      "perso-3-city-44",
      "perso-3-city-45",
      "perso-3-city-46",
      "perso-3-city-47",
      "perso-3-city-48",
      "perso-3-city-49",
      "perso-3-city-50",
      "perso-3-city-51",
      "perso-3-city-52",
      "perso-3-city-53"
    ],
    "scall": 1
  },
  {
    "src": "./img/asset-items/perso-3-other.png",
    "name": "perso-3-other",
    "imgHeight": 224,
    "imgWidth": 192,
    "assetCount": 20,
    "type": "perso",
    "images": [
      "perso-3-other-0",
      "perso-3-other-1",
      "perso-3-other-2",
      "perso-3-other-3",
      "perso-3-other-4",
      "perso-3-other-5",
      "perso-3-other-6",
      "perso-3-other-7",
      "perso-3-other-8",
      "perso-3-other-9",
      "perso-3-other-10",
      "perso-3-other-11",
      "perso-3-other-12",
      "perso-3-other-13",
      "perso-3-other-14",
      "perso-3-other-15",
      "perso-3-other-16",
      "perso-3-other-17",
      "perso-3-other-18",
      "perso-3-other-19"
    ],
    "scall": 1
  },
  {
    "src": "./img/asset-opti/ItemGrave.png",
    "name": "ItemGrave",
    "images": [
      "gravestoneDecorative",
      "coffinOld",
      "gravestoneRound",
      "altarStone",
      "gravestoneBevel",
      "crypt",
      "gravestoneFlat",
      "gravestoneRoof",
      "gravestoneFlatOpen",
      "gravestoneWide",
      "coffin",
      "altarWood"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "items",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/Town1.png",
    "name": "Town1",
    "images": [
      "wallCurved",
      "roofCornerRound",
      "wallDoor",
      "wallDoorwaySquareWideCurved",
      "wallRounded",
      "wallSlope",
      "wallSide",
      "wallArchTop",
      "wallCornerDetail",
      "wallWindowSmall",
      "wallDetailCross",
      "wallWindowRound",
      "wallArchTopDetail",
      "wallWindowStone",
      "wallCornerDiagonalHalf",
      "roofPoint",
      "roofCorner",
      "roofRight",
      "wallDetailDiagonal",
      "roofWindow",
      "roofGableTop",
      "wallDoorwayRound",
      "wallCornerDiagonal",
      "wallBlockHalf",
      "roofGableDetail",
      "wallArch",
      "wallCornerEdge",
      "roofGableEnd",
      "wallDetailHorizontal",
      "wallDiagonal",
      "roofGable",
      "wallDoorwayBase",
      "roofFlat",
      "wallDoorwaySquareWide",
      "roof",
      "wallBlock",
      "roofCornerInner",
      "wallHalf",
      "wall",
      "wallDoorwaySquare",
      "wallBroken",
      "wallWindowShutters",
      "wallCorner",
      "roofLeft",
      "wallWindowGlass"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "building",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/AstroRocket.png",
    "name": "AstroRocket",
    "images": [
      "rocket_fuelB",
      "rocket_sidesA",
      "rocket_finsA",
      "rocket_baseB",
      "rocket_topA",
      "rocket_sidesB",
      "rocket_fuelA",
      "rocket_topB",
      "rocket_finsB",
      "rocket_baseA"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "items",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/Train.png",
    "name": "Train",
    "images": [
      "monorail_trainFront",
      "monorail_trainEnd",
      "monorail_trackSlope",
      "pipe_entrance",
      "monorail_trainBox",
      "pipe_supportHigh",
      "pipe_split",
      "monorail_trainFlat",
      "monorail_trainCargo",
      "monorail_trackSupport",
      "monorail_trackStraight",
      "pipe_end",
      "monorail_trackSupportCorner",
      "pipe_cornerDiagonal",
      "pipe_straight",
      "pipe_ringHighEnd",
      "pipe_cross",
      "pipe_rampLarge",
      "pipe_ringHigh",
      "pipe_ring",
      "pipe_corner",
      "monorail_trackCornerSmall",
      "monorail_trainPassenger",
      "pipe_cornerRound",
      "pipe_supportLow",
      "pipe_open",
      "pipe_ringSupport"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "items-train",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/AstroBase.png",
    "name": "AstroBase",
    "images": [
      "corridor_open",
      "corridor_windowClosed",
      "corridor_",
      "corridor_cornerRoundWindow",
      "corridor_cross",
      "corridor_corner",
      "corridor_window",
      "corridor_detailed",
      "corridor_end",
      "corridor_cornerRound",
      "corridor_roof",
      "corridor_split",
      "corridor_wallCorner",
      "corridor_wall"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "building",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/UserAstro.png",
    "name": "UserAstro",
    "images": [],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "perso",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/NatureRock.png",
    "name": "NatureRock",
    "images": [
      "rock_largeA",
      "rockSmall",
      "debrisWood",
      "stone_smallFlatB",
      "stone_largeB",
      "stone_smallC",
      "stone_smallTopA",
      "platform_stone",
      "stone_tallB",
      "debris",
      "stone_smallA",
      "rockLarge",
      "stone_tallD",
      "stone_tallH",
      "stone_smallE",
      "stone_largeD",
      "stone_smallI",
      "rock_crystalsLargeA",
      "rocksTall",
      "meteor",
      "rock_crystals",
      "meteor_detailed",
      "platform_beach",
      "rocks",
      "stone_tallJ",
      "stone_tallF",
      "rocks_smallB",
      "stone_largeF",
      "stone_smallG",
      "platform_grass",
      "stone_tallC",
      "stone_smallB",
      "stone_largeC",
      "stone_smallFlatC",
      "stone_smallFlatA",
      "rock_largeB",
      "stone_tallA",
      "stone_smallTopB",
      "crater",
      "rock",
      "stone_largeA",
      "craterLarge",
      "stone_largeE",
      "stone_smallD",
      "stone_smallH",
      "rocks_smallA",
      "stone_tallE",
      "stone_tallI",
      "meteor_half",
      "stone_smallF",
      "stone_tallG",
      "rockWide",
      "rock_crystalsLargeB"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "items-nature",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/AstroPlatform.png",
    "name": "AstroPlatform",
    "images": [
      "platform_center",
      "platform_small",
      "structure_closed",
      "platform_corner",
      "platform_cornerOpen",
      "platform_side",
      "platform_high",
      "platform_low",
      "platform_cornerRound",
      "structure",
      "platform_smallDiagonal",
      "platform_end",
      "structure_diagonal",
      "supports_high",
      "platform_straight",
      "structure_detailed",
      "supports_low",
      "platform_cornerDot",
      "platform_centerA"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "building",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/ItemOther.png",
    "name": "ItemOther",
    "images": [
      "crate",
      "barrel",
      "detailPlate",
      "bench",
      "heart",
      "campfire_logs",
      "flag",
      "chest",
      "chimney",
      "spikesHidden",
      "key",
      "crateStrong",
      "coinSilver",
      "bones",
      "road",
      "detailBowl",
      "crateItemStrong",
      "benchDamaged",
      "coinGold",
      "spikesLarge",
      "detailChalice",
      "sign",
      "chimney_detailed",
      "jewel",
      "urn",
      "arrows",
      "tent_detailedClosed",
      "arrow",
      "crateItem",
      "spikes",
      "tent_detailedOpen",
      "campfire_stones",
      "coinBronze"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "items",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/Wall.png",
    "name": "Wall",
    "images": [
      "fence_simpleLow",
      "fenceGate",
      "fence_bend",
      "doorClosed",
      "fence_simpleDiagonal",
      "fence_gate",
      "doorOpen",
      "hedge",
      "fence_simpleHigh",
      "fence_planks",
      "ironFenceBorder",
      "fence_simpleCenter",
      "fence_bendCenter",
      "fence_simpleDiagonalCenter",
      "brickWallCurve",
      "stoneWallDamaged",
      "fence_planksDouble",
      "brickWall",
      "stoneWall",
      "ironFence",
      "stoneWallCurve",
      "ironFenceBar",
      "rail_middle",
      "hedgeCorner",
      "ironFenceDamaged",
      "fence_corner",
      "ironFenceBorderColumn",
      "ironFenceCurve",
      "fence_simple",
      "ironFenceBorderGate",
      "rail_end",
      "fence_",
      "rail_corner",
      "stoneWallColumn",
      "ironFenceBorderCurve",
      "fenceDamaged",
      "rail"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "building",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/NatureTree.png",
    "name": "NatureTree",
    "scall": true,
    "images": [
      "tree_detailed",
      "tree_thin_fall",
      "tree_palmShort",
      "tree_small",
      "tree_pineDefaultA",
      "tree_thin_dark",
      "cactus_tall",
      "tree_pineRoundE",
      "tree_cone",
      "tree_tall_dark",
      "tree_blocks_fall",
      "tree_cone_fall",
      "tree_default_fall",
      "tree_pineTallC",
      "tree_pineRoundA",
      "tree_simple_dark",
      "tree_pineRoundC",
      "tree_simple_fall",
      "tree_pineTallA",
      "tree_default",
      "tree_simple",
      "tree_default_dark",
      "tree_cone_dark",
      "tree_tall_fall",
      "tree_pineSmallA",
      "tree_blocks_dark",
      "tree_palmTall",
      "tree_thin",
      "tree_pineSmallD",
      "tree_fat",
      "tree_fat_darkh",
      "tree_oak_fall",
      "tree_pineTallD",
      "tree_plateau_fall",
      "tree_detailed_dark",
      "tree_palmBend",
      "tree_pineRoundD",
      "tree_detailed_fall",
      "tree_oak_dark",
      "tree_plateau_dark",
      "tree_palmDetailedShort",
      "cactus_short",
      "tree_small_fall",
      "tree_pineTallB",
      "tree_palmDetailedTall",
      "tree_fat_fall",
      "tree_pineSmallB",
      "tree_blocks",
      "tree_palm",
      "tree_oak",
      "tree_pineGroundA",
      "tree_tall",
      "tree_small_dark",
      "tree_pineRoundB",
      "tree_plateau"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "items-nature"
  },
  {
    "src": "./img/asset-opti/ItemPilar.png",
    "name": "ItemPilar",
    "images": [
      "statue_column",
      "statue_ring",
      "statue_obelisk",
      "pillarSquare",
      "statue_head",
      "pillarObelisk",
      "statue_block",
      "pillarLarge",
      "borderPillar",
      "pillarSmall",
      "statue_columnDamaged",
      "columnLarge"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "items",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/Town2.png",
    "name": "Town2",
    "images": [
      "wallWoodArchTopDetail",
      "wallWoodCornerDiagonal",
      "wallWood",
      "wallWoodArch",
      "roofHighGableTop",
      "wallWoodCurved",
      "wallWoodDoorwayRound",
      "wallWoodBlockHalf",
      "roofHighGableDetail",
      "wallWoodDetailCross",
      "wallWoodWindowStone",
      "wallWoodWindowRound",
      "wallWoodWindowSmall",
      "wallWoodWindowShutters",
      "wallWoodDetailHorizontal",
      "roofHighCornerInner",
      "wallWoodCornerDiagonalHalf",
      "roofHighPoint",
      "poles",
      "roofHighRight",
      "wallWoodBlock",
      "wallWoodCornerEdge",
      "wallWoodHalf",
      "roofHigh",
      "roofHighCornerRound",
      "wallWoodRounded",
      "wallWoodSide",
      "wallWoodDiagonal",
      "wallWoodWindowGlass",
      "wallWoodSlope",
      "roofHighFlat",
      "wallWoodDoorwaySquareWideCurved",
      "wallWoodDoor",
      "roofHighGable",
      "wallWoodArchTop",
      "wallWoodDoorwaySquare",
      "wallWoodDetailDiagonal",
      "roofHighGableEnd",
      "wallWoodDoorwayBase",
      "polesHorizontal",
      "wallWoodCorner",
      "roofHighWindow",
      "wallWoodDoorwaySquareWide",
      "roofHighLeft",
      "wallWoodBroken",
      "roofHighCorner"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "building",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/ItemTech.png",
    "name": "ItemTech",
    "images": [
      "barrels_rail",
      "satelliteDish_large",
      "barrels",
      "machine_barrel",
      "gate_simple",
      "satelliteDish",
      "machine_generator",
      "gate_complex",
      "machine_wirelessCable",
      "machine_generatorLarge",
      "satelliteDish_detailed",
      "machine_wireless",
      "machine_barrelLarge"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "items",
    "scall": 1
  },
  {
    "src": "./img/asset-opti/NatureFlower.png",
    "name": "NatureFlower",
    "scall": true,
    "images": [
      "mushroom_redTall",
      "crops_bambooStageB",
      "crops_cornStageA",
      "flower_purpleA",
      "grass_large",
      "crops_cornStageC",
      "flower_purpleC",
      "flower_redB",
      "grass",
      "crops_wheatStageB",
      "plant_flatTall",
      "flower_yellowC",
      "plant_bushLarge",
      "mushroom_tan",
      "flower_yellowA",
      "plant_bush",
      "plant_bushSmall",
      "crops_leafsStageA",
      "lily_small",
      "mushroom_redGroup",
      "plant_bushDetailed",
      "flower_redA",
      "mushroom_red",
      "crops_bambooStageA",
      "flower_redC",
      "lily_large",
      "flower_purpleB",
      "crops_cornStageB",
      "plant_flatShort",
      "grass_leafs",
      "mushroom_tanTall",
      "flower_yellowB",
      "plant_bushTriangle",
      "crops_leafsStageB",
      "grass_leafsLarge",
      "mushroom_tanGroup",
      "crops_cornStageD",
      "crops_wheatStageA",
      "plant_bushLargeTriangle"
    ],
    "imgHeight": 224,
    "imgWidth": 192,
    "type": "items-nature"
  }
] as AssetConfigLoaded[];
