// personality
// behavior

export const CITIZEN_NAME: any = {
  prefixes: [
    "Zar",
    "Xan",
    "Quar",
    "Val",
    "Nor",
    "Gal",
    "Elo",
    "Tyr",
    "Lun",
    "Vor",
    "Kyl",
    "Mer",
    "Rax",
    "Fen",
    "Jor",
    "Zyl",
    "Tor",
    "Drak",
    "Mor",
    "Sol",
    "Dax",
    "Nyx",
    "Ren",
    "Vos",
    "Kir",
    "Jax",
    "Lyn",
    "Mav",
    "Pax",
    "Sor",
    "Zan",
    "Nex",
    "Kal",
    "Wor",
    "Jad",
    "Syr",
    "Taz",
    "Vel",
    "Xor",
    "Bex",
  ],
  infixes: [
    "ax",
    "or",
    "en",
    "is",
    "ul",
    "an",
    "er",
    "os",
    "il",
    "un",
    "ik",
    "ar",
    "el",
    "et",
    "im",
    "od",
    "ur",
    "as",
    "em",
    "ix",
    "yn",
    "ot",
    "ir",
    "es",
    "om",
    "il",
    "ek",
    "ur",
    "av",
    "id",
    "az",
    "og",
    "ev",
    "ut",
    "is",
    "on",
    "it",
    "ar",
    "um",
    "ov",
  ],
  suffixes: [
    "ar",
    "on",
    "us",
    "ix",
    "an",
    "en",
    "es",
    "or",
    "is",
    "ul",
    "ak",
    "in",
    "as",
    "et",
    "um",
    "ir",
    "al",
    "ok",
    "os",
    "ur",
    "ad",
    "el",
    "ix",
    "am",
    "un",
    "er",
    "av",
    "im",
    "ol",
    "iz",
    "eg",
    "ur",
    "ok",
    "is",
    "or",
    "ul",
    "et",
    "iv",
    "om",
    "ar",
  ],
  titles: [
    "Captain",
    "Commander",
    "Lieutenant",
    "Doctor",
    "Agent",
    "General",
    "Admiral",
    "Professor",
    "Colonel",
    "Major",
    "Sergeant",
    "Technician",
    "Navigator",
    "Pilot",
    "Scout",
    "Ambassador",
    "Envoy",
    "Warden",
    "Guardian",
    "Protector",
    "Overseer",
    "Specialist",
    "Strategist",
    "Operative",
    "Chief",
    "Inquisitor",
    "Enforcer",
    "Marshal",
    "Pathfinder",
    "Sentinel",
    "Monitor",
    "Tracker",
    "Custodian",
    "Surveyor",
    "Regent",
    "Archon",
    "Vanguard",
    "Artificer",
    "Technomancer",
    "Recon",
  ],
};

CITIZEN_NAME.rand = () => {
  const prefixes = CITIZEN_NAME.prefixes; // ["Zar", "Xan", "Quar", "Val", "Nor", "Gal", "Elo", "Tyr", "Lun", "Vor", "Kyl", "Mer", "Rax", "Fen", "Jor", "Zyl", "Tor", "Drak", "Mor", "Sol"];
  const infixes = CITIZEN_NAME.infixes; // ["ax", "or", "en", "is", "ul", "an", "er", "os", "il", "un", "ik", "ar", "el", "et", "im", "od", "ur", "as", "em", "ix"];
  const suffixes = CITIZEN_NAME.suffixes; // ["ar", "on", "us", "ix", "an", "en", "es", "or", "is", "ul", "ak", "in", "as", "et", "um", "ir", "al", "ok", "os", "ur"];
  const titles = CITIZEN_NAME.titles; // ["Captain", "Commander", "Lieutenant", "Doctor", "Agent", "General", "Admiral", "Professor", "Colonel", "Major", "Sergeant", "Technician", "Navigator", "Pilot", "Scout", "Ambassador", "Envoy", "Warden", "Guardian", "Protector"];

  const getRandomElement = (array: string[]): string =>
    array[Math.floor(Math.random() * array.length)];

  const getRandomInt = (max: number) => Math.floor(Math.random() * max);

  // Decide the structure of the name: prefix+infix+suffix or prefix+infix+infix+suffix
  const structure: string[][] = [prefixes, infixes, suffixes];

  // Generate the base name
  const name = structure.map(getRandomElement).join("");

  // Optionally add a title
  // if (getRandomInt(4) === 0) { // 25% chance to add a title
  //     name = `${getRandomElement(titles)} ${name}`;
  // }

  return name;
};

export const CITIZEN_TRAIS = {
  // trais personality
  personality: {
    "introverted": "😶",
    "extroverted": "😄",
    "adventurous": "🏞️",
    "cautious": "🚦",
    "optimistic": "😊",
    "pessimistic": "😞",
    "ambitious": "💼",
    "lazy": "😴",
    "spontaneous": "🎉",
    "meticulous": "🔍",
    "impulsive": "💥",
    "methodical": "📊",
    "whimsical": "🌈",
    "conscientious": "📝",
    "laid_back": "😎",
    "uptight": "👔",
  },
  // behavior
  behavior: {
    "take charge": "👊",
    "follow": "👥",
    "impulsive": "💥",
    "planner": "📅",
    "laid-back": "😎",
    "overthinker": "🤔",
    "rebel": "🤘",
    "conformist": "👍",
    "overenthusiastic": "🤩",
    "laziness": "😴",
    "nerdiness": "🤓",
    "clumsiness": "🤹‍♂️",
    "silliness": "🤪",
    "stubbornness": "💢",
    "people-pleaser": "🙇‍♂️",
    "sarcasm": "🙄",
    "daydreamer": "💭",
    "realist": "🧐",
    "eccentric": "🎩",
    "goody-two-shoes": "👼",
    "dramatic": "🎭",
    "easy-to-please": "😊",
    "forgetful": "🤦‍♂️",
    "dutiful": "📝",
  },
  // emotional_responses
  emotional: {
    "resilient": "💪",
    "sensitive": "😢",
    "stoic": "😐",
    "melodramatic": "🎭",
    "overdramatic": "😱",
    "zen": "🧘‍♂️",
    "paranoid": "👀",
    "nonchalant": "😏",
    "dramatic": "🎬",
    "chaotic": "🌀",
    "clueless": "🤷‍♂️",
    "awkward": "😬",
    "enigmatic": "🕵️‍♂️",
    "hyperactive": "🤪",
    "zombie-like": "🧟‍♂️",
    "robotic": "🤖",
    "jovial": "😄",
    "emo": "🖤",
    "savage": "😈",
    "perplexed": "🤔",
    "peckish": "😋",
    "giggly": "😆",
    "sassy": "💁‍♂️",
    "gloomy": "😞",
    "sparkling": "✨",
    "moody": "😒",
    "determined": "👊",
    "bewildered": "😵",
    "giddy": "🤩",
    "frazzled": "😖",
    "blissful": "😌",
    "indifferent": "😑",
    "twitchy": "😬",
    "flabbergasted": "😲",
    "ecstatic": "😍",
    "bemused": "😕",
    "apathetic": "😑",
    "nostalgic": "📼",
    "zen-like": "🧘‍♂️",
    "frenzied": "😵‍💫",
    "blase": "😒",
    "lovestruck": "😍",
    "hyper": "🚀",
  },

  // interests_hobbies
  hobbies: {
    "gardening": "🌱",
    "reading": "📚",
    "geology": "⛰️",
    "high-tech": "🔬",
    "space_discovery": "🚀",
    "painting": "🎨",
    "photography": "📷",
    "cooking": "👨‍🍳",
    "traveling": "✈️",
    "birdwatching": "🦜",
    "fishing": "🎣",
    "playing musical instruments": "🎸",
    "knitting": "🧶",
    "hiking": "🥾",
    "yoga": "🧘‍♂️",
    "gaming": "🎮",
    "writing": "✍️",
    "baking": "🍰",
    "dancing": "💃",
    "surfing": "🏄‍♂️",
    "sculpting": "🗿",
    "calligraphy": "🖋️",
    "woodworking": "🪵",
    "sewing": "🧵",
    "collecting stamps": "📬",
    "playing chess": "♟️",
    "astronomy": "🔭",
    "rock climbing": "🧗‍♂️",
    "skydiving": "🪂",
    "cycling": "🚴‍♂️",
    "meditation": "🧘‍♂️",
    "pottery": "🏺",
    "volunteering": "🤝",
    "karaoke": "🎤",
    "DIY projects": "🛠️",
    "wine tasting": "🍷",
    "learning languages": "🗣️",
    "watching movies": "🎬",
    "solving puzzles": "🧩",
  },
  // hightech_civilization
  highTech: {
    "Cutting-edge": "🔪🔍",
    "Digitalized": "💻💡",
    "Futuristic": "🚀🔮",
    "Sustainable": "♻️💡",
    "Smart City": "🏙️💡",
    "Immersive": "🕶️🔊",
    "Biotech": "🧬💉",
    "Nano": "🔬🌱",
    "Cybersecurity": "🔒💻",
    "Quantum Computing": "💻🔮",
    "3D Printing": "🖨️🏗️",
    "Augmented Reality": "👓🌍",
    "Blockchain": "🔗💻",
    "Space Exploration": "🚀🌌",
    "Artificial General Intelligence": "🤖🧠",
    "Internet of Things (IoT)": "🌐🏠",
    "Neural Interfaces": "🧠💻",
    "Quantum Teleportation": "🔮✨",
    "Biometric Identification": "🔑🧬",
    "Energy Harvesting": "⚡💡",
    "Robotic Assistants": "🤖👩‍💼",
    "Smart Fabrics": "👕🌐",
    "Hydroponic Farming": "🌱💧",
    "Solar Power Satellites": "🛰️☀️",
    "Genetic Modification": "🧬🧬",
    "Mind Uploading": "🧠💾",
    "Space Elevators": "🛰️🏗️",
    "Cybernetic Enhancements": "🤖🦾",
    "Astroengineering": "🌌🏗️",
    "Mind-Control Technology": "🧠🤯",
    "Teleportation Devices": "🔮✨",
    "Augmented Humans": "🧍🔍",
    "Genomic Editing": "🧬✂️",
    "Space Habitats": "🌌🏠",
    "Bio-Printing": "🧬🖨️",
    "Energy Storage Solutions": "⚡💾",
  },
  // quirky_technologies
  quirkyTech: {
    "Innovative Gadgets": "🔧🔍",
    "Futuristic Gizmos": "🚀🔭",
    "Quirky Inventions": "🤪💡",
    "Baffling Contraptions": "🤔🔧",
    "Whimsical Machines": "⚙️🌀",
    "Steampunk Creations": "⚙️🔩",
    "Eclectic Innovations": "🔮💡",
    "Surreal Apparatus": "🌀🔧",
    "Mad Scientist Creations": "🔬🧪",
    "Cosmic Contrivances": "🌌🔧",
    "Time-Travel Gizmos": "⏳🔧",
    "Dimensional Devices": "🌐🔧",
    "Nano-scale Creations": "🔍🔬",
    "Bio-mechanical Marvels": "🦠🤖",
    "Antique Automatons": "⚙️🕰️",
    "Robotic Oddities": "🤖🔧",
    "Fantasy Contrivances": "🐉🔧",
    "Apocalyptic Artifacts": "☢️🔧",
    "Retro-futuristic Relics": "🛸🔧",
    "Alien Artifacts": "👽🔧",
    "Enigmatic Mechanisms": "❓⚙️",
    "Hilarious Contraptions": "😂🔧",
    "Cute Gadgets": "🐱🔌",
    "Surreal Devices": "🌀📱",
    "Whacky Inventions": "🤪🔬",
    "Cyberpunk Creations": "🤖💻",
    "Virtual Reality Wonders": "🕶️🌐",
    "Augmented Reality Marvels": "👓🌐",
    "Nanotech Marvels": "🔬🌱",
    "Genetic Engineering Marvels": "🧬🔬",
    "Artificial Intelligence Creations": "🤖🧠",
    "Biomechanical Innovations": "🦾🧬",
    "Cyborg Gadgets": "🤖👾",
    "Psychedelic Machines": "🌀💡",
    "Mind-bending Contraptions": "🧠🔧",
    "Neurotech Wonders": "🧠💻",
    "Quantum Computing Devices": "⚛️💻",
    "Holographic Projections": "🔮🖥️",
    "Bionic Implants": "🦾💉",
    "Wireless Energy Transmitters": "⚡📡",
    "Space Exploration Innovations": "🚀🌌",
    "Astronomical Instruments": "🔭🌟",
    "Oceanic Technology Marvels": "🌊🔧",
    "Renewable Energy Gadgets": "♻️🔋",
    "Sustainable Living Tools": "🌱🔧",
    "3D Printing Wonders": "🖨️🌟",
  },

  // -----------
  // Narative
  // -----------
  // cure
  curse: {
    "Possessed": "👻",
    "Hexed": "🔮",
    "Dark Magic": "🧙‍♂️",
    "Maleficent": "🧙‍♀️",
    "Wicked": "🦹‍♂️",
    "Malediction": "💀",
    "Diabolic": "👺",
    "Sinister Aura": "🌑",
    "Evil Eye": "👁️",
    "Demonic": "👿",
    "Catastrophic": "⚠️",
    "Baleful": "😱",
    "Ghoulish": "🧟",
    "Dreadful": "😨",
    "Foreboding": "⚔️",
    "Cursed Soul": "🪆",
    "Jinxed": "🔖",
    "Voodoo": "🗿",
    "Spellbound": "🔒",
    "Witchcraft": "🔥",
    "Enchanted": "✨",
    "Taboo": "🚫",
    "Supernatural": "👽",
    "Infernal": "🌳",
    "Malefic": "👹",
    "Eldritch": "🐙",
    "Fatal": "🌟",
    "Mystic": "💀",
    "Necromantic": "☠️",
  },
  // wft_effect
  wftEffect: {
    "Mind-bending": "🌀🤯",
    "Reality-warping": "🌌🔄",
    "Twisted": "🌀😵",
    "Alien": "👽🌌",
    "Anomalous": "🔍❓",
    "Absurd": "🤪🔄",
    "Unclassifiable": "❓🔍",
    "Mind-melting": "🤯🍦",
    "Outrageous": "😱🔄",
    "Grotesque": "😬🌀",
    "Inexplicable": "❓🔍",
    "Bizarre": "🌀🤔",
    "Quirky": "🤪🔄",
    "Offbeat": "🎵🔄",
    "Weird": "🤔🌀",
    "Peculiar": "🔍🔄",
    "Freaky": "😱🌀",
    "Absurdly": "🤪🔄",
    "Paradoxical": "❓🔄",
    "Mind-boggling": "🤯🔍",
    "Ridiculous": "🤪🔄",
    "Mind-blowing": "🤯💥",
    "Freaky-deaky": "😱🌀",
    "Beyond comprehension": "🔍🔄",
    "Outrageously absurd": "😱🤪",
    "Otherworldly": "👽🌌",
    "Beyond belief": "😱🔍",
    "Enigmatic": "🤔❓",
    "Crazy town": "🤪🏘️",
    "Bonkers": "🤪🌀",
    "Off-the-charts": "📈🔄",
    "Beyond the pale": "😱🔄",
    "Batshit crazy": "🦇💩",
    "Mind-numbing": "🤯💥",
    "Beyond the matrix": "🔍🔄",
    "Mind-bendingly strange": "🌀🤔",
    "Crazy cool": "🤪😎",
    "Out of this world": "🌍🔄",
    "Surrealistic": "🖼️🌀",
    "Twilight Zone": "🌌🌀",
    "Mind-altering": "🤯🔄",
    "Out-of-place": "❓🌍",
    "Unpredictable": "❓🔮",
    "Chaos-inducing": "🌀😱",
    "Reality-shattering": "🌌💔",
    "Temporal anomaly": "⏳❓",
    "Dimensional rift": "🔍🌀",
    "Existential crisis": "🔄😱",
    "Reality inversion": "🔄🌌",
    "Mind-crushing": "🤯💥",
    "Inexplicably weird": "❓🌀",
    "Incomprehensibly strange": "❓🌀",
    "Existentially disorienting": "🔄😵",
  },
  // irony_and_utter_bewilderment
  irony: {
    "Ironic Situations": "🤔😂",
    "Bewildering Events": "😳🌀",
    "Unexpected Twists": "🔄😱",
    "Situational Irony": "🤷‍♂️😅",
    "Bewildering Circumstances": "🤨🔄",
    "Unexpected Developments": "🔄😲",
    "Comically Contradictory": "😂🔄",
    "Enigmatic Mysteries": "🕵️‍♂️🔍",
    "Supernatural Oddities": "👻🌀",
    "Quizzical Coincidences": "🤔🎲",
    "Fantastically Absurd": "🦄🤪",
    "Whimsically Wacky": "🎩🤪",
    "Absurdly Amusing": "🤪😂",
    "Surreally Silly": "😵🤪",
    "Unbelievable Ironies": "🤯😂",
    "Confounding Enigmas": "🤷‍♂️🕵️‍♂️",
    "Mind-Bending Twists": "🤯😱",
    "Surreal Oddities": "😵🌀",
    "Hilarious Ironies": "😂🤷‍♂️",
    "Unpredictable Anomalies": "🤷‍♂️😳",
    "Absurd Absurdities": "🤪🤪",
    "Wacky Wackiness": "🤪🎩",
    "Ridiculous Antics": "🤪😆",
    "Fantasy Fantasies": "🦄✨",
    "Comic Absurdities": "😆🤪",
    "Whimsical Whimsies": "🤪✨",
    "Paradoxical Paradoxes": "🤷‍♂️🔄",
    "Ludicrous Laughter": "😆😂",
    "Zany Zaniness": "🤪🤪",
    "Absurd Absurdities 2": "🤪🤪",
    "Bizarre Coincidences": "😳🎲",
    "Surreal Whimsies": "😵✨",
    "Ludicrous Laughter 2": "😆😂",
    "Whimsically Weirdness": "✨🤪",
    "Comic Oddities": "😆🌀",
    "Paradoxical Antics": "🤷‍♂️😆",
    "Fantasy Fantasies 2": "🦄✨",
    "Unpredictable Whims": "🤷‍♂️✨",
    "Whimsical Wonders": "✨🤪",
    "Fantastical Follies": "🦄😆",
    "Fanciful Nonsense": "✨🤷‍♂️",
    "Silly Shenanigans": "🤪😆",
    "Fanciful Frivolity": "✨🤪",
    "Hilarious Hilarity": "😂😂",
    "Fanciful Farce": "✨🤷‍♂️",
  },

  // -----------

  "Neighbor Cleverness": {
    "Sly Intelligence": "",
    "Street Smart": "",
    "Quick-wittedness": "",
    "Resourcefulness": "",
  },
  "strengths_weaknesses": {
    "strengths": "",
    "weaknesses": "",
    "quirks": "",
    "superpowers": "",
  },
  "background_life_experiences": {
    "family": "",
    "education": "",
    "career": "",
    "relationships": "",
  },
  "attitude_towards_others": {
    "friendly": "",
    "reserved": "",
    "outgoing": "",
    "aloof": "",
    "charming": "",
    "abrasive": "",
    "whimsical": "",
    "stoic": "",
    "helpful": "",
    "manipulative": "",
    "blunt": "",
    "naive": "",
    "critical": "",
    "eccentric": "",
    "affectionate": "",
  },
  "values_beliefs": {
    "principles": "",
    "open-mindedness": "",
    "tradition": "",
    "ambition": "",
    "community": "",
  },
};
