import { TypeAssetGroupConfig } from "../../assetOptiConfig.ts";
import { list_to_asset } from "../../assetUtils.ts";

export const asset_Train: TypeAssetGroupConfig = {
  "src": "./img/asset-opti/items/Train.png",
  "group": "Train",
  "images": list_to_asset([
    "monorail_trainFront",
    "monorail_trainEnd",
    "monorail_trackSlope",
    "pipe_entrance",
    "monorail_trainBox",
    "pipe_supportHigh",
    "pipe_split",
    "monorail_trainFlat",
    "monorail_trainCargo",
    "monorail_trackSupport",
    "monorail_trackStraight",
    "pipe_end",
    "monorail_trackSupportCorner",
    "pipe_cornerDiagonal",
    "pipe_straight",
    "pipe_ringHighEnd",
    "pipe_cross",
    "pipe_rampLarge",
    "pipe_ringHigh",
    "pipe_ring",
    "pipe_corner",
    "monorail_trackCornerSmall",
    "monorail_trainPassenger",
    "pipe_cornerRound",
    "pipe_supportLow",
    "pipe_open",
    "pipe_ringSupport",
  ]),
  "imgHeight": 224,
  "imgWidth": 192,
};
