import { TypeAssetGroupConfig } from "../../assetOptiConfig.ts";
import { list_to_asset } from "../../assetUtils.ts";

export const asset_NatureRock: TypeAssetGroupConfig = {
  "src": "./img/asset-opti/environement/NatureRock.png",
  "group": "NatureRock",
  "images": list_to_asset([
    "rock_largeA",
    "rockSmall",
    "debrisWood",
    "stone_smallFlatB",
    "stone_largeB",
    "stone_smallC",
    "stone_smallTopA",
    "platform_stone",
    "stone_tallB",
    "debris",
    "stone_smallA",
    "rockLarge",
    "stone_tallD",
    "stone_tallH",
    "stone_smallE",
    "stone_largeD",
    "stone_smallI",
    "rock_crystalsLargeA",
    "rocksTall",
    "meteor",
    "rock_crystals",
    "meteor_detailed",
    "platform_beach",
    "rocks",
    "stone_tallJ",
    "stone_tallF",
    "rocks_smallB",
    "stone_largeF",
    "stone_smallG",
    "platform_grass",
    "stone_tallC",
    "stone_smallB",
    "stone_largeC",
    "stone_smallFlatC",
    "stone_smallFlatA",
    "rock_largeB",
    "stone_tallA",
    "stone_smallTopB",
    "crater",
    "rock",
    "stone_largeA",
    "craterLarge",
    "stone_largeE",
    "stone_smallD",
    "stone_smallH",
    "rocks_smallA",
    "stone_tallE",
    "stone_tallI",
    "meteor_half",
    "stone_smallF",
    "stone_tallG",
    "rockWide",
    "rock_crystalsLargeB",
  ]),
  "imgHeight": 224,
  "imgWidth": 192,
};
