import { TypeAssetGroupConfig } from "../../assetOptiConfig.ts";
import { list_to_asset } from "../../assetUtils.ts";

export const asset_Town2: TypeAssetGroupConfig = {
  "src": "./img/asset-opti/structure/Town2.png",
  "group": "Town2",
  "images": list_to_asset([
    "wallWoodArchTopDetail",
    "wallWoodCornerDiagonal",
    "wallWood",
    "wallWoodArch",
    "roofHighGableTop",
    "wallWoodCurved",
    "wallWoodDoorwayRound",
    "wallWoodBlockHalf",
    "roofHighGableDetail",
    "wallWoodDetailCross",
    "wallWoodWindowStone",
    "wallWoodWindowRound",
    "wallWoodWindowSmall",
    "wallWoodWindowShutters",
    "wallWoodDetailHorizontal",
    "roofHighCornerInner",
    "wallWoodCornerDiagonalHalf",
    "roofHighPoint",
    "poles",
    "roofHighRight",
    "wallWoodBlock",
    "wallWoodCornerEdge",
    "wallWoodHalf",
    "roofHigh",
    "roofHighCornerRound",
    "wallWoodRounded",
    "wallWoodSide",
    "wallWoodDiagonal",
    "wallWoodWindowGlass",
    "wallWoodSlope",
    "roofHighFlat",
    "wallWoodDoorwaySquareWideCurved",
    "wallWoodDoor",
    "roofHighGable",
    "wallWoodArchTop",
    "wallWoodDoorwaySquare",
    "wallWoodDetailDiagonal",
    "roofHighGableEnd",
    "wallWoodDoorwayBase",
    "polesHorizontal",
    "wallWoodCorner",
    "roofHighWindow",
    "wallWoodDoorwaySquareWide",
    "roofHighLeft",
    "wallWoodBroken",
    "roofHighCorner",
  ]),
  "imgHeight": 224,
  "imgWidth": 192,
};
