import { TypeAssetGroupConfig } from "../../assetOptiConfig.ts";
import { list_to_asset } from "../../assetUtils.ts";

export const asset_Town1: TypeAssetGroupConfig = {
  "src": "./img/asset-opti/structure/Town1.png",
  "group": "Town1",
  "images": list_to_asset([
    "wallCurved",
    "roofCornerRound",
    "wallDoor",
    "wallDoorwaySquareWideCurved",
    "wallRounded",
    "wallSlope",
    "wallSide",
    "wallArchTop",
    "wallCornerDetail",
    "wallWindowSmall",
    "wallDetailCross",
    "wallWindowRound",
    "wallArchTopDetail",
    "wallWindowStone",
    "wallCornerDiagonalHalf",
    "roofPoint",
    "roofCorner",
    "roofRight",
    "wallDetailDiagonal",
    "roofWindow",
    "roofGableTop",
    "wallDoorwayRound",
    "wallCornerDiagonal",
    "wallBlockHalf",
    "roofGableDetail",
    "wallArch",
    "wallCornerEdge",
    "roofGableEnd",
    "wallDetailHorizontal",
    "wallDiagonal",
    "roofGable",
    "wallDoorwayBase",
    "roofFlat",
    "wallDoorwaySquareWide",
    "roof",
    "wallBlock",
    "roofCornerInner",
    "wallHalf",
    "wall",
    "wallDoorwaySquare",
    "wallBroken",
    "wallWindowShutters",
    "wallCorner",
    "roofLeft",
    "wallWindowGlass",
  ]),
  "imgHeight": 224,
  "imgWidth": 192,
};
